# Generated by Django 3.0.14 on 2022-10-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STG_HH_Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_id', models.IntegerField()),
                ('premium', models.BooleanField()),
                ('name', models.TextField()),
                ('has_test', models.BooleanField()),
                ('response_letter_required', models.BooleanField()),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('archived', models.BooleanField()),
                ('alternate_url', models.URLField()),
                ('area_id', models.IntegerField()),
                ('area_name', models.TextField()),
                ('salary_from', models.FloatField()),
                ('salary_to', models.FloatField()),
                ('salary_currency', models.TextField()),
                ('salary_gross', models.BooleanField()),
                ('type_id', models.IntegerField()),
                ('type_name', models.TextField()),
                ('employer_id', models.IntegerField()),
                ('employer_name', models.TextField()),
                ('employer_alternate_url', models.URLField()),
                ('employer_logo_urls_original', models.URLField()),
                ('employer_vacancies_url', models.URLField()),
                ('employer_trusted', models.BooleanField()),
                ('snippet_requirement', models.TextField()),
                ('snippet_responsibility', models.TextField()),
                ('schedule_id', models.IntegerField()),
                ('schedule_name', models.TextField()),
                ('address_city', models.TextField()),
                ('address_street', models.TextField()),
                ('address_building', models.TextField()),
                ('address_lat', models.TextField()),
                ('address_lng', models.FloatField()),
                ('address_raw', models.FloatField()),
                ('address_metro_station_name', models.TextField()),
                ('address_metro_line_name', models.TextField()),
                ('address_metro_lat', models.FloatField()),
                ('address_metro_lng', models.FloatField()),
            ],
            options={
                'verbose_name': 'Вакансии с сайта hh.ru',
                'verbose_name_plural': 'Вакансии с сайта hh.ru',
                'db_table': 'STG_Vacancy_hh_ru',
            },
        ),
    ]
