# Generated by Django 3.0.14 on 2022-10-10 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
