# Generated by Django 3.0.14 on 2022-10-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_vacancy_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterModelTable(
            name='city',
            table='City',
        ),
        migrations.AlterModelTable(
            name='language',
            table='Language',
        ),
        migrations.AlterModelTable(
            name='vacancy',
            table='Vacancy',
        ),
    ]
