# Generated by Django 3.0.14 on 2022-10-22 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20221022_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='stg_hh_vacancy',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='stg_hh_vacancy',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
