# Generated by Django 3.0.14 on 2022-10-23 01:56

from django.db import migrations
import jsonfield.fields
import scraping.models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='url',
        ),
        migrations.AddField(
            model_name='url',
            name='url_data',
            field=jsonfield.fields.JSONField(default=scraping.models.default_url),
        ),
    ]
