# Generated by Django 3.0.14 on 2022-10-23 03:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_auto_20221023_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'URL', 'verbose_name_plural': 'URLs'},
        ),
        migrations.RemoveField(
            model_name='stg_hh_vacancy',
            name='modified',
        ),
        migrations.AlterField(
            model_name='stg_hh_vacancy',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
